const lang = {
    1: {
        id: "1",
        success: "成功",
        normalError: "常规错误",
        argError: "参数错误",
        connectionError: "网络连接错误，请稍后重试",
        pointNotEnough: "积分不足",
        noExpress: "没有物流信息",
        tokenError: "登陆信息过期，请重新登陆后再试",
        requestFail: "连接服务器失败，请确认您的网络连接",
        responseFail: "请求失败",
        prizeHistory: "抽奖记录",
        prizeCreateTime: "获奖时间",
        prize1Status: ["待发奖", "待发奖", "已发放", "发放失败"],
        prize2Status: ["待填写信息", "充值中", "充值成功", "充值失败"],
        prize3Status: ["待填写信息", "运输中", "已签收", "签收失败"],
        prize4Status: ["待发奖", "待发奖", "查看", "发放失败"],
        noticeTitle: "活动说明",
        noticeLine1: "抽奖获得的钻石,阅读券,VIP即时生效",
        noticeLine2: "实物类奖品自中奖时间起7天内可领取,逾期则视为自动放弃领奖",
        noticeLine3: "实物和话费奖品将在您提交正确联系信息后7个工作日内安排发货,请耐心等待",
        noticeLine4: "若因地址不正确,联系号码错误,停机等个人原因导致快递多次配送部成功,我们将视为自动放弃领奖",
        noticeLine5: "奖品非质量问题不作退还,敬请谅解",
        noticeLine6: "若因个人原因拒绝签收奖品,我们将保留通过法律途径要求用户补偿运费损失的权利",
        noticeLine7: "通过非法途径获得奖品的,主办方有权不提供奖品",
        currencySymbol: "Rp",
        currencyPoint: ",",
        currencySeparator: ".",
        congratulations: "恭喜",
        refusePrize: "我不想要",
        refusePrizeNotice: "如果你不喜欢这个奖品，可以选择我不想要",
        refusePrizeSuccess: "已放弃奖品",
        recivePrize: "立即领取",
        confirmPrize: "确认",
        tabNotRecive: "未领取",
        tabRecived: "已领取",
        chargePhoneNum: "您本次充值话费的电话号码",
        chargePhoneSubmit: "提交",
        receiveAwardNoticeTitle: "特别提醒",
        receiveAwardNoticeLine1: "1.若因地址不详,联系号码错误,停机等个人原因导致快递多次配送不成功,延期退回后我们将不再进行二次发货,非质量问题不退换,敬请谅解.",
        receiveAwardNoticeLine2: "2.如有疑问可直接联系客服.",
        facebookUrl: "https://www.facebook.com/RayMangaID",
        lazadaUrl: "https://www.facebook.com/RayMangaID",
        chargePhoneSubmitSuccess: "提交成功，我们将尽快为您充值，请关注您的话费余额",
        noPhoneNum: "请输入手机号",
        gotoLazada: "去LAZADA RAYMANGA官方店铺购买任何商品，结算时填写该券码，可直接抵扣对应现金",
        copyToClipboard: "点我复制到剪切板",
        copyToClipboardSuccess: "复制成功，马上去Raymanga官方商店使用吧",
        copyToClipboardFail: "复制失败，请手动复制",
        expressSubmitSuccess: "提交成功，我们将尽快为您快递奖品",
        expressName: "收货人姓名",
        expressPhone: "收货人电话",
        expressCountry: "国家",
        expressState: "省",
        expressCity: "城市",
        expressDistrict: "区",
        expressAddress: "详细地址",
        expressCost: "快递费用和时间",
        expressNoticeLine1: "1.如果您的地址不在选择范围内,请直接联系客服.",
        expressNoticeLine2: "2.快递费用将在奖品送达时由快递公司向您收取.",
        expressNoticeLine3: "3.我们会在您提交联系方式之后2天内发货,请耐心等待.",
        expressSubmit: "提交",
        expressNumber: "快递单号",
    },
    2: {
        id: "2",
        requestFail: "连接服务器失败，请确认您的网络连接",
        responseFail: "请求失败",

    },
    3: {
        id: "3",
        requestFail: "连接服务器失败，请确认您的网络连接",
        responseFail: "请求失败",
    }
};
export default lang;
